addSbtPlugin("pl.project13.scala" % "sbt-jmh"                % "0.4.7")
addSbtPlugin("org.typelevel"      % "sbt-typelevel"          % "0.6.5")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-scalafix" % "0.6.5")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-site"     % "0.6.5")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"            % "1.14.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"       % "0.4.16")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"          % "2.0.9")
